セッション周りの実装
tomonobusaijo/protospace pull request #6
Opened 2016-09-17 09:35 UTC by tomonobusaijo

# WHAT
セッション周り(サインイン、サインアップ、サインアウト)の実装
# WHY
ユーザー管理を簡潔にするため

2016-09-17 09:39 UTC, hc070208 commented on app/views/devise/registrations/new.html.haml
> +/       %button.btn.btn-lg.btn-primary.btn-block{type: "submit"} Save
不要なコメントアウトは今のうちに消しましょう！

2016-09-17 09:40 UTC, hc070208 commented on app/views/layouts/_header.html.haml
> +              %a{href: "/users/sign_in"}
link_toに書き換えていただきたいです。

2016-09-17 09:40 UTC, hc0208 requested changes

2016-09-17 10:04 UTC, tomonobusaijo commented
確認し、修正しました！ありがとうございます。

2016-09-19 05:05 UTC, merged

2016-09-19 05:46 UTC, naokishizuka commented on app/views/layouts/_header.html.haml
> +                = link_to 'My Page', user_path(current_user.id)
user_pathなどのurlを生成するメソッドの引数にはインスタンスを入れるだけでidに変換してくれます。
ですので、この場合
user_path(current_user)
としたほうがスッキリとしていて良いでしょう！

2016-09-19 05:48 UTC, naokishizuka commented on app/views/layouts/application.html.haml
> +      %div{class: "alert alert-#{key}", style:"margin-bottom: 0px;"}= value
読みづらいので=valueは改行してあげましょう。

2016-09-19 06:04 UTC, tomonobusaijo commented
確認ありがとうございます！いずれも修正いたしました。